# Generated by Django 4.2.23 on 2025-08-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_configuration', '0005_alter_location_name_and_more'),
        ('sample_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.ForeignKey(limit_choices_to={'location_type__can_store_samples': True}, on_delete=django.db.models.deletion.PROTECT, to='location_configuration.location')),
            ],
        ),
    ]
