# Generated by Django 4.2.23 on 2025-08-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryControlAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_inventorycontrol_page', 'Can view the main inventory control page')],
                'managed': False,
            },
        ),
    ]
