# Generated by Django 4.2.23 on 2025-08-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_configuration', '0002_locationtype_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='locationtype',
            name='description',
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='location_configuration.location'),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='allowed_parents',
            field=models.ManyToManyField(blank=True, to='location_configuration.locationtype'),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='can_store_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='can_store_samples',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='columns',
            field=models.PositiveIntegerField(blank=True, help_text='Number of columns for the spaces grid', null=True),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='has_spaces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='icon',
            field=models.CharField(blank=True, help_text="e.g., 'warehouse', 'room', 'freezer'", max_length=100),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='rows',
            field=models.PositiveIntegerField(blank=True, help_text='Number of rows for the spaces grid', null=True),
        ),
        migrations.CreateModel(
            name='LocationSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('child_location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_space', to='location_configuration.location')),
                ('parent_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='location_configuration.location')),
            ],
            options={
                'unique_together': {('parent_location', 'row', 'column')},
            },
        ),
    ]
