# Generated by Django 4.2.23 on 2025-08-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_configuration', '0003_remove_location_barcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationconfigurationaccess',
            options={'managed': False, 'permissions': [('view_locationconfiguration_tab', 'Can view the main location configuration tab')]},
        ),
    ]
