# Generated by Django 4.2.23 on 2025-08-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_configuration', '0004_alter_locationconfigurationaccess_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='allowed_parents',
            field=models.ManyToManyField(blank=True, related_name='allowed_children', to='location_configuration.locationtype'),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='columns',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='icon',
            field=models.CharField(blank=True, help_text="e.g., 'warehouse', 'room', 'shelves'", max_length=100),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='rows',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
